#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'aspnet_Users'
    /// </summary>
    public partial class AspnetUser
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetUser"/> class.
        /// </summary>
        public AspnetUser()
        {
            #region Generated Constructor

            AspnetUsersInRoles = new HashSet<AspnetUsersInRole>();

            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'ApplicationId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ApplicationId'.
        /// </value>
        public Guid ApplicationId { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'UserId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'UserId'.
        /// </value>
        public Guid UserId { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'UserName'.
        /// </summary>
        /// <value>
        /// The property value representing column 'UserName'.
        /// </value>
        public string UserName { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'LoweredUserName'.
        /// </summary>
        /// <value>
        /// The property value representing column 'LoweredUserName'.
        /// </value>
        public string LoweredUserName { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'MobileAlias'.
        /// </summary>
        /// <value>
        /// The property value representing column 'MobileAlias'.
        /// </value>
        public string? MobileAlias { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'IsAnonymous'.
        /// </summary>
        /// <value>
        /// The property value representing column 'IsAnonymous'.
        /// </value>
        public bool IsAnonymous { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'LastActivityDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'LastActivityDate'.
        /// </value>
        public DateTime LastActivityDate { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="AspnetApplication" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="AspnetApplication" />.
        /// </value>
        /// <seealso cref="ApplicationId" />
        public AspnetApplication? AspnetApplication { get; set; }

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="AspnetMembership" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="AspnetMembership" />.
        /// </value>
        /// <seealso cref="UserId" />
        public AspnetMembership? AspnetMembership { get; set; }

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="AspnetProfile" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="AspnetProfile" />.
        /// </value>
        /// <seealso cref="UserId" />
        public AspnetProfile? AspnetProfile { get; set; }

        /// <summary>
        /// Gets or sets the navigation collection for entity <see cref="AspnetUsersInRole" />.
        /// </summary>
        /// <value>
        /// The the navigation collection for entity <see cref="AspnetUsersInRole" />.
        /// </value>
        public virtual ICollection<AspnetUsersInRole> AspnetUsersInRoles { get; set; }

        #endregion // Generated Relationships
    }
}
