#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetSchemaVersion" />
    /// </summary>
    public partial class AspnetSchemaVersionMap
        : IEntityTypeConfiguration<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetSchemaVersion>
    {
        /// <summary>
        /// Configures the entity of type <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetSchemaVersion" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetSchemaVersion> builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("aspnet_SchemaVersions", "dbo");

            // key
            builder.HasKey(t => new {
                t.Feature,
                t.CompatibleSchemaVersion
            });
            

            // properties
            builder.Property(t => t.Feature)
                .IsRequired()
                .HasColumnName("Feature")
                .HasColumnType("nvarchar(128)")
                .HasMaxLength(128)
                ;
            builder.Property(t => t.CompatibleSchemaVersion)
                .IsRequired()
                .HasColumnName("CompatibleSchemaVersion")
                .HasColumnType("nvarchar(128)")
                .HasMaxLength(128)
                ;
            builder.Property(t => t.IsCurrentVersion)
                .IsRequired()
                .HasColumnName("IsCurrentVersion")
                .HasColumnType("bit")
                ;

            // relationships

            #endregion // Generated Configure
        }
    }
}
