#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'aspnet_Profile'
    /// </summary>
    public partial class AspnetProfile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetProfile"/> class.
        /// </summary>
        public AspnetProfile()
        {
            #region Generated Constructor


            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'UserId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'UserId'.
        /// </value>
        public Guid UserId { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'PropertyNames'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PropertyNames'.
        /// </value>
        public string PropertyNames { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'PropertyValuesString'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PropertyValuesString'.
        /// </value>
        public string PropertyValuesString { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'PropertyValuesBinary'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PropertyValuesBinary'.
        /// </value>
        public Byte[] PropertyValuesBinary { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'LastUpdatedDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'LastUpdatedDate'.
        /// </value>
        public DateTime LastUpdatedDate { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="AspnetUser" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="AspnetUser" />.
        /// </value>
        /// <seealso cref="UserId" />
        public AspnetUser? AspnetUser { get; set; }

        #endregion // Generated Relationships
    }
}
