#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'aspnet_SchemaVersions'
    /// </summary>
    public partial class AspnetSchemaVersion
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetSchemaVersion"/> class.
        /// </summary>
        public AspnetSchemaVersion()
        {
            #region Generated Constructor


            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'Feature'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Feature'.
        /// </value>
        public string Feature { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'CompatibleSchemaVersion'.
        /// </summary>
        /// <value>
        /// The property value representing column 'CompatibleSchemaVersion'.
        /// </value>
        public string CompatibleSchemaVersion { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'IsCurrentVersion'.
        /// </summary>
        /// <value>
        /// The property value representing column 'IsCurrentVersion'.
        /// </value>
        public bool IsCurrentVersion { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        #endregion // Generated Relationships
    }
}
