#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'aspnet_UsersInRoles'
    /// </summary>
    public partial class AspnetUsersInRole
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetUsersInRole"/> class.
        /// </summary>
        public AspnetUsersInRole()
        {
            #region Generated Constructor


            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'UserId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'UserId'.
        /// </value>
        public Guid UserId { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'RoleId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'RoleId'.
        /// </value>
        public Guid RoleId { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="AspnetRole" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="AspnetRole" />.
        /// </value>
        /// <seealso cref="RoleId" />
        public AspnetRole? AspnetRole { get; set; }

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="AspnetUser" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="AspnetUser" />.
        /// </value>
        /// <seealso cref="UserId" />
        public AspnetUser? AspnetUser { get; set; }

        #endregion // Generated Relationships
    }
}
