#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'RolePermissions'
    /// </summary>
    public partial class RolePermission
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RolePermission"/> class.
        /// </summary>
        public RolePermission()
        {
            #region Generated Constructor


            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'RoleName'.
        /// </summary>
        /// <value>
        /// The property value representing column 'RoleName'.
        /// </value>
        public string RoleName { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'PermissionId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PermissionId'.
        /// </value>
        public string PermissionId { get; set; } = default!;

        #endregion // Generated Properties

        #region Generated Relationships

        #endregion // Generated Relationships
    }
}
