#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.RolePermission" />
    /// </summary>
    public partial class RolePermissionMap
        : IEntityTypeConfiguration<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.RolePermission>
    {
        /// <summary>
        /// Configures the entity of type <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.RolePermission" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.RolePermission> builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("RolePermissions", "dbo");

            // key
            builder.HasKey(t => new {
                t.RoleName,
                t.PermissionId
            });
            

            // properties
            builder.Property(t => t.RoleName)
                .IsRequired()
                .HasColumnName("RoleName")
                .HasColumnType("nvarchar(128)")
                .HasMaxLength(128)
                .HasDefaultValueSql("('')")
                ;
            builder.Property(t => t.PermissionId)
                .IsRequired()
                .HasColumnName("PermissionId")
                .HasColumnType("nvarchar(322)")
                .HasMaxLength(322)
                .HasDefaultValueSql("('')")
                ;

            // relationships

            #endregion // Generated Configure
        }
    }
}
