#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'aspnet_Membership'
    /// </summary>
    public partial class AspnetMembership
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetMembership"/> class.
        /// </summary>
        public AspnetMembership()
        {
            #region Generated Constructor


            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'ApplicationId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ApplicationId'.
        /// </value>
        public Guid ApplicationId { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'UserId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'UserId'.
        /// </value>
        public Guid UserId { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Password'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Password'.
        /// </value>
        public string Password { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'PasswordFormat'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PasswordFormat'.
        /// </value>
        public int PasswordFormat { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'PasswordSalt'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PasswordSalt'.
        /// </value>
        public string PasswordSalt { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'MobilePIN'.
        /// </summary>
        /// <value>
        /// The property value representing column 'MobilePIN'.
        /// </value>
        public string? MobilePIN { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Email'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Email'.
        /// </value>
        public string? Email { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'LoweredEmail'.
        /// </summary>
        /// <value>
        /// The property value representing column 'LoweredEmail'.
        /// </value>
        public string? LoweredEmail { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'PasswordQuestion'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PasswordQuestion'.
        /// </value>
        public string? PasswordQuestion { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'PasswordAnswer'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PasswordAnswer'.
        /// </value>
        public string? PasswordAnswer { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'IsApproved'.
        /// </summary>
        /// <value>
        /// The property value representing column 'IsApproved'.
        /// </value>
        public bool IsApproved { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'IsLockedOut'.
        /// </summary>
        /// <value>
        /// The property value representing column 'IsLockedOut'.
        /// </value>
        public bool IsLockedOut { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'CreateDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'CreateDate'.
        /// </value>
        public DateTime CreateDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'LastLoginDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'LastLoginDate'.
        /// </value>
        public DateTime LastLoginDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'LastPasswordChangedDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'LastPasswordChangedDate'.
        /// </value>
        public DateTime LastPasswordChangedDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'LastLockoutDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'LastLockoutDate'.
        /// </value>
        public DateTime LastLockoutDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'FailedPasswordAttemptCount'.
        /// </summary>
        /// <value>
        /// The property value representing column 'FailedPasswordAttemptCount'.
        /// </value>
        public int FailedPasswordAttemptCount { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'FailedPasswordAttemptWindowStart'.
        /// </summary>
        /// <value>
        /// The property value representing column 'FailedPasswordAttemptWindowStart'.
        /// </value>
        public DateTime FailedPasswordAttemptWindowStart { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'FailedPasswordAnswerAttemptCount'.
        /// </summary>
        /// <value>
        /// The property value representing column 'FailedPasswordAnswerAttemptCount'.
        /// </value>
        public int FailedPasswordAnswerAttemptCount { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'FailedPasswordAnswerAttemptWindowStart'.
        /// </summary>
        /// <value>
        /// The property value representing column 'FailedPasswordAnswerAttemptWindowStart'.
        /// </value>
        public DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Comment'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Comment'.
        /// </value>
        public string? Comment { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="AspnetApplication" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="AspnetApplication" />.
        /// </value>
        /// <seealso cref="ApplicationId" />
        public AspnetApplication? AspnetApplication { get; set; }

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="AspnetUser" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="AspnetUser" />.
        /// </value>
        /// <seealso cref="UserId" />
        public AspnetUser? AspnetUser { get; set; }

        #endregion // Generated Relationships
    }
}
