#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'vw_aspnet_Profiles'
    /// </summary>
    public partial class VwAspnetProfile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VwAspnetProfile"/> class.
        /// </summary>
        public VwAspnetProfile()
        {
            #region Generated Constructor


            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'UserId'.
        /// </summary>
        /// <value>
        /// The property value representing column 'UserId'.
        /// </value>
        public Guid UserId { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'LastUpdatedDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'LastUpdatedDate'.
        /// </value>
        public DateTime LastUpdatedDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'DataSize'.
        /// </summary>
        /// <value>
        /// The property value representing column 'DataSize'.
        /// </value>
        public int? DataSize { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        #endregion // Generated Relationships
    }
}
