#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data
{
    /// <summary>
    /// A <see cref="DbContext" /> instance represents a session with the database and can be used to query and save instances of entities.
    /// </summary>
    public partial class AspNetMembershipContext : DbContext
    {
        private const string DesignTimeProvider = "SqlServer";
        private const string DesignTimeConnectionString = "";
        private const string DesignTimeConnectionName = "AspNetMembership";
        private const string DesignTimeUserSecretsId = "Zyborg.AspNetCore.Identity.AspNetMembership";


        /// <summary>
        /// Initializes a new instance of the <see cref="AspNetMembershipContext"/> class.
        /// </summary>
        /// <param name="options">The options to be used by this <see cref="DbContext" />.</param>
        public AspNetMembershipContext(DbContextOptions<AspNetMembershipContext> options)
            : base(options)
        {
        }

        #region Generated Properties
        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetApplication"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetApplication"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetApplication> AspnetApplications { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetMembership"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetMembership"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetMembership> AspnetMemberships { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetProfile"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetProfile"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetProfile> AspnetProfiles { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetRole"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetRole"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetRole> AspnetRoles { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetSchemaVersion"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetSchemaVersion"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetSchemaVersion> AspnetSchemaVersions { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetUser"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetUser"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetUser> AspnetUsers { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetUsersInRole"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetUsersInRole"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.AspnetUsersInRole> AspnetUsersInRoles { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.RolePermission"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.RolePermission"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.RolePermission> RolePermissions { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetApplication"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetApplication"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetApplication> VwAspnetApplications { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetMembershipUser"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetMembershipUser"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetMembershipUser> VwAspnetMembershipUsers { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetProfile"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetProfile"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetProfile> VwAspnetProfiles { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetRole"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetRole"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetRole> VwAspnetRoles { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetUser"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetUser"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetUser> VwAspnetUsers { get; set; } = default!;

        /// <summary>
        /// Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetUsersInRole"/>.
        /// </summary>
        /// <value>
        /// The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of <see cref="Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetUsersInRole"/>.
        /// </value>
        public virtual DbSet<Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Entities.VwAspnetUsersInRole> VwAspnetUsersInRoles { get; set; } = default!;

        #endregion // Generated Properties

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            if (!optionsBuilder.IsConfigured)
            {
                var connString = DesignTimeConnectionString;
                if (string.IsNullOrWhiteSpace(connString))
                {
                    // We don't have the design-time connection string
                    // but we might have design-time user secrets info,
                    // which can be used as an opportunity to resolve
                    ResolveUserSecretsConnectionString(DesignTimeUserSecretsId, DesignTimeConnectionName, ref connString);
                }

                optionsBuilder.UseSqlServer(connString);
            }
        }

        partial void ResolveUserSecretsConnectionString(string userSecretsId, string connName, ref string connString);

        /// <summary>
        /// Configure the model that was discovered from the entity types exposed in <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> properties on this context.
        /// </summary>
        /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            #region Generated Configuration
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.AspnetApplicationMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.AspnetMembershipMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.AspnetProfileMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.AspnetRoleMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.AspnetSchemaVersionMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.AspnetUserMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.AspnetUsersInRoleMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.RolePermissionMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.VwAspnetApplicationMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.VwAspnetMembershipUserMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.VwAspnetProfileMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.VwAspnetRoleMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.VwAspnetUserMap());
            modelBuilder.ApplyConfiguration(new Zyborg.AspNetCore.Identity.AspNetMembership.Membership.Data.Mapping.VwAspnetUsersInRoleMap());
            #endregion // Generated Configuration
        }
    }
}
